version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: synapse_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend-web:
    build: ./backend-web
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/synapse_db
      - PORT=5000
      - AI_BACKEND_URL=http://backend-ai:8000
    depends_on:
      - db
    volumes:
      - ./backend-web:/app
      - /app/node_modules
    command: sh -c "npx prisma db push && npm run dev"

  backend-ai:
    build: ./backend-ai
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@synapse.ai
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
